version: "3.7"
services:
  server:
    image: straoke-api
    container_name: straoke-api
    build: .
    ports:
      - "8081:8080"
networks:
    default:
        external: true
        name: network-jenkins